### ISSUE TITLE
Test Instructions

### ISSUE THREAD

**Issue by dalow** [hackingchips/PSoC_RFM69#1]
Thank-you for building this lib. Sorry to bother you.
I am having trouble using the test set up for PSoc_RFM69.
I reduced power to 10. Slave and master are about .5M apart on the same computer.
I am using CYC8kit-049 psoc 4200. The master seems to be working. 
RED LED blinks 2X then stays on.
I submit command "A" .. then I get ->. 
Master test case A Start...Master test case A after xmit...Waiting data from Slave 1...TimedOut...
Select test :>

Nothing happens on the slave side.

Slave looks like this->
Looking for RFM69 module... OK
SLAVE_1... Waiting...

the slave does not accept any commands.

What am I doing wrong?
Thanks for your help
Doug

**Comment by hackingchips** [comment]
I am out of  home until tuesday and without access to my computer and my circuits. 
If you can wait until then, i will be in a better position to help you with your code.

**Comment by dalow** [comment]
ok thanks

**Comment by hackingchips** [comment]
dalow...
in the following link you can download a new test.
it was compiled for PSoC 4M using CY8CKIT-044 development kit, because all my other dev kits are occupied with other projects. 

https://drive.google.com/file/d/0B4ENO1ZtN8s_TlpzTnhjeWlQcnM/view?usp=sharing

With proper adaptation (pinout, serial port...) it should work with your kit too.

Are you using CYC8kit-049 as it comes from factory? 
RFM69 modules works at 3.3 volts (unless they are mounted in some kind of dev board with voltage regulator and spi signals adaptation). If you use CYC8kit-049 kit as it comes from factory, it uses 5V from USB bus, then you will need to adapt spi bus levels and some kind of 3.3 voltage regulator for the RFM module. 

Let me know if you can make the code to work with your kit. If not, then i can try to adapt it in a few days for CYC8kit-049 kit.

**Comment by dalow** [comment]
I'm using adafruit rfm69 Board that regulates signals to 3.3v so it can be
used for 5 or 3.3v.
Thanks ill give it a try tomorrow.

**Comment by dalow** [comment]
I used your new code. Not sure what the difference is.
I changed the uP to cyc84245AXI-483 which is the one for the cy8ckit-049-42xx.
Again I am using the adafruit RFM69HCW radio board that regulates the signal voltages to 3.3v.
I changed the power level from 31 to 5 in the config file. I should get signal power of -18 +5 =-13dB.
The boards are about .5m apart on the same computer.
I connected:
CS to SPI:sso_m (pretty sure this is correct)
G0 to RFM_INT (must be right)
RST to RFM_RESET (must be right)
MOSI,MISO, SCK,VIN,GND as appropriate (self expainitory)
LEDS installed on the slave and they work
Left EN unconnected (Maybe this is wrong but I read that it is connected internally)
Attached 6.5" wire to each antenna pad according to adafruit instructions .
Compiled one board as master using the main.h
Compiled the other as slave 1
Both boards using interrupts based on main.h

Operation:
set up 2 terminal programs, one for each port: 19200,8,1,n
plugged in slave, then master.
LEDS work according to program, RED blinks 2X then Green lights and stays on.

Got this on the slave terminlal:( removed some line feeds)
Looking for RFM69 module... OK
SLAVE_1... Waiting...

Got this on the master terminal: ( removed some line feeds)
Looking for RFM69 module... OK
PSoC RFM69 Test... PSoC 4/4M... MASTER
Options:
    1 - Slave 1: Toggle red led.
    2 - Slave 1: Toggle green led.
    3 - Slave 1: Toggle blue led.
    A - Slave 1: Read temperature...
    ? - This menu.
Select test :> 

no matter what I select on the master I get nothing on the slave.

So it looks like the program is running, LEDs work, communicating with the terminal as well as the RMF69HCW.
Any ideas? am I doing something wrong?

**Comment by hackingchips** [comment]
I was looking at Adafruit page and reading about their RFM69 module. The problem (i think) is they are using the high power version of the RFM69 module (RFM69HW) and, until now, this library only supports the low power or normal module (RFM69W).
Both modules uses diferent internal power stages, so some changes have to be made to the library. I have this in my TODO list (also adding support for PSoC 5LP) and i have received RFM69HW modules about two weeks ago but i have not had the time to implement necesary changes.

If you want to try by yourself, you can try the following changes:
- add a function to the library to set/unset the high power mode, for example:

```
// if mode = 1 set H mode. if mode = 0, set normal mode or RX mode.

void RFM69_SetHMode(uint8 mode)
{
    if (mode == 1) // H mode for H modules
    {
        RFM69_Register_Write(REG_TESTPA_1, 0x5D);
        RFM69_Register_Write(REG_TESTPA_2, 0x7C);
    }
    else if (mode == 0) // normal modules and RX mode.
    {
        RFM69_Register_Write(REG_TESTPA_1, 0x55);
        RFM69_Register_Write(REG_TESTPA_2, 0x70);
    }
}
```
- And then modify the 'SetMode' function:

```
void RFM69_SetMode(uint8 mode) 
{
    /* If operation mode = RX, then set DIO0 for interrupt when PayloadReady.
       If operation mode = TX, then set DIO0 for interrupt when PacketSent. 
    */
    if (mode == OP_MODE_RX)
    {
        RFM69_SetHMode(0); // set low power for RX
        RFM69_Register_Write(REG_DIOMAPPING_1, 0x40);
    }
    else if (mode == OP_MODE_TX)
    {
        RFM69_SetHMode(1); // set high power for TX
        RFM69_Register_Write(REG_DIOMAPPING_1, 0x00);
    }

    RFM69_Register_Write(REG_OPMODE, mode);
    mRFM69_WaitModeReady();
}
```

RFM69HW modules have to be configured for high power during transmision and low power during reception.

Please, realize that i have not tested this code in a real circuit. I think it should work but it is possible that some other changes are needed.

I will implement these changes and implement support for PSoC 5LP as soon as i have the time.

If you want to learn something more about RFM69 modules, André Heßling has an interesting article in his blog:
https://www.andrehessling.de/2015/02/07/figuring-out-the-power-level-settings-of-hoperfs-rfm69-hwhcw-modules/

**Comment by dalow** [comment]
Excellent. I'll give it a try and let you know how it works out. Thanks so
much for your help.
